### ISSUE TITLE
Clouds aren't infinite

### ISSUE THREAD

**Issue by EliteAsian123** [EliteAsian123/noa-plus-plugins#1]
Anybody know how to make the clouds infinite in NoaEnvironment without making the clouds follow the player?

**Comment by levlups** [comment]
I think you have to make them huge ,player cant get to the end ???

**Comment by EliteAsian123** [comment]
Yeah I made the width and height of the plane `2e3` and that's the max. I can get to the end of them in about 2 minutes.

**Comment by EliteAsian123** [comment]
I figured it out. I made the clouds follow the player BUT I made the uvs scroll so it looks like they are in the same place.
